@startuml
left to right direction

actor DA as "Data Analyst"

rectangle "World Database"

rectangle "United Nations App System" {
    usecase UC1 as "Generate country report"
    usecase UC2 as "Generate city report"
    usecase UC3 as "Generate capital city report"
    usecase UC4 as "Generate population report"

    DA -- UC1
    DA -- UC2
    DA -- UC3
    DA -- UC4

    UC1 -- "World Database"
    UC2 -- "World Database"
    UC3 -- "World Database"
    UC4 -- "World Database"
}

@enduml
