@startuml
actor USR as "User"

rectangle "Database"

rectangle "App System" {
    usecase UC1 as "Get capital cities by population at geographical level
    or top N populated capital cities"
    usecase UC1a as "Generate Report"

    USR - UC1

    UC1 - Database

    UC1 ..> UC1a : <<include>>

}
@enduml